# 端口配置
server:
  port: 5091

# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://YOUR_DB_HOST:3306/mms_dev_core?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true

# Swagger 配置
springdoc:
  swagger-ui:
    url: /base/v3/api-docs

# 文件上传配置
file:
  upload:
    # 允许的文件类型（扩展名，小写）
    allowed-types:
      - jpg
      - jpeg
      - png
      - gif
      - bmp
      - webp
      - doc
      - docx
      - xls
      - xlsx
      - ppt
      - pptx
      - pdf
      - txt
    # 单个文件最大大小（MB）
    max-size: 50
    # 存储路径
    storage-path: /data/mms/attachments
    # 访问URL前缀
    url-prefix: /base/api/files/download
    # 是否启用文件类型验证（MIME类型 + 扩展名双重验证）
    enable-type-validation: true