# 端口配置
server:
  port: 5091

# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://111.229.150.28:3306/mms_dev_core?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true
  servlet:
    multipart:
      # Multipart 上传限制（需要 >= file.upload.max-size，否则请求在进入 Controller 前就会被拦截）
      max-file-size: 50MB
      max-request-size: 50MB

# Swagger 配置
springdoc:
  swagger-ui:
    url: /base/v3/api-docs

# 文件上传配置
file:
  upload:
    # 允许的文件类型（扩展名，小写）
    allowed-types:
      - jpg
      - jpeg
      - png
      - gif
      - bmp
      - webp
      - doc
      - docx
      - xls
      - xlsx
      - ppt
      - pptx
      - pdf
      - txt
      - md
    # 单个文件最大大小（MB）
    max-size: 50
    # 存储路径（相对路径）
    storage-path: ./attachments
    # 访问URL前缀
    url-prefix:  /base/attachment/stream
    # 批量上传最大文件数量
    max-batch-count: 10
    # 是否启用文件去重（基于文件MD5，暂不启用）
    enable-deduplication: false
    # 文件访问权限控制
    access-control:
      # 是否启用权限校验
      enabled: true
      # 允许访问的角色（为空则所有登录用户可访问）
      allowed-roles: []
      # 是否允许创建者访问自己的文件
      allow-creator-access: true
    # 文件清理配置（本地开发可关闭）
    cleanup:
      # 是否启用自动清理
      enabled: false
      # 清理已删除文件的时间间隔（天）
      deleted-file-retention-days: 30
      # 清理任务执行时间（cron表达式）
      cleanup-cron: "0 0 2 * * ?"  # 每天凌晨2点
    # 文件预览配置
    preview:
      # 是否启用预览功能
      enabled: true
      # 支持预览的文件类型
      supported-types:
        - jpg
        - jpeg
        - png
        - gif
        - pdf
      # 图片预览最大尺寸（像素）
      image-max-size: 1920