# Redis配置
spring:
  data:
    redis:
      host: YOUR_REDIS_HOST
      port: YOUR_REDIS_PORT
      password: YOUR_REDIS_PASSWORD
      timeout: 3000ms
      lettuce:
        pool:
          max-wait: -1ms
          max-active: 8
          max-idle: 8
          min-idle: 2