# 端口配置
server:
  port: 5090

# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://YOUR_DB_HOST:3306/mms_dev_core?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true

# 登录安全配置
login:
  security:
    max-attempts: 5   # 最大登录失败次数
    lock-time: 30  # 锁定时间（分钟）
    attempt-key-prefix: "login_attempts:"  # 登录失败次数缓存前缀
    lock-key-prefix: "account_lock:"  # 账号锁定缓存前缀

# Swagger 配置
springdoc:
  swagger-ui:
    url: /usercenter/v3/api-docs